tasks:
  - name: Dependencies
    before: |
      sudo pip uninstall virtualenv
      sudo pip install virtualenv
      virtualenv /workspace/venv
    init: |
      . /workspace/venv/bin/activate
      /workspace/venv/bin/python -m pip install poetry
      poetry install
    command: |
      . /workspace/venv/bin/activate
