tasks:
  - name: Dependencies
    before: |
      virtualenv /workspace/venv
    init: |
      . /workspace/venv/bin/activate
      /workspace/venv/bin/python -m pip install poetry
      poetry install
